language: haskell
ghc:
  - 7.8
  - 7.6

before_script:
  - curl -sS -o roundup https://raw.githubusercontent.com/bmizerany/roundup/v0.0.5/roundup.sh

script:
  cabal configure && cabal build && make test -e ROUNDUP='/bin/bash roundup'
